name: Test

jobs:
  build:
    name: Test Build OFRP by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
- name: Find All omni_X663.mk Files
  run: |
    cd ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1
    echo "=== SEARCHING FOR ALL omni_X663.mk FILES ==="
    find . -name "omni_X663.mk" -type f
    echo "==========================================="